packages <- c("devtools",
              "foreign",
              "tidyverse",
              "Cairo",
              "knitr",
              "lazyeval",
              "classInt",
              "reshape2",
              "lmtest",
              "car",
              "downloader",
              "coda",
              "R2admb",
              "dgof",
              "victim",
              "glmmADMB",
              "pbapply"
          )
